#!/bin/sh
#
# Problems? Sugestions? Contact me here: https://github.com/NoTengoBattery/openwrt/issues

. /lib/ntb/irq.sh

disable_fw_log() {
  local debug_level=/sys/kernel/debug/ieee80211/$1/ath10k/debug_level
  printf "0x10000000" > "$debug_level"
}

configure_ct() {
  local special=/sys/kernel/debug/ieee80211/$1/ath10k/ct_special
  if [ -e "$special" ]; then
    printf "0x100100000140"   > "$special"  # Firmware kickout [ 20 * 16 ]
    printf "0x1000000001" > "$special"  # Enable receiving all mgt frames
  fi
}

set_ani() {
  local ani=/sys/kernel/debug/ieee80211/$1/ath10k/ani_enable
  printf $2 > "$ani"  # 0: disable ANI; 1: enable ANI
}

set_rates() {  # http://mcsindex.com
  local ht_mcs="15"
  local vht_msc="2:9"
  local legacy=2.4
  local b=2.4
  iw dev $1 set bitrates
  case "$2" in
    *"a000000.wifi"*)
      b=2.4
      legacy=2.4
    ;;
    *"a800000.wifi"*)
      b=5
      legacy=24
    ;;
  esac
  iw dev $1 set bitrates legacy-$b $legacy ht-mcs-$b $ht_mcs vht-mcs-$b $vht_msc sgi-$b force-sgi
}

if [ "x$ACTION" = "xadd" ] && [ "x$DEVTYPE" = "xwlan" ]; then
  DEVICE=$(readlink -f /sys/$DEVPATH)
  DRIVER=$(basename $(readlink $DEVICE/device/driver))
  if [ "x$DRIVER" = "xath10k_ahb" ]; then
    NET=$INTERFACE
    PHY=$(ls $DEVICE/device/ieee80211)
    printf "ath10k: added a new wireless network interface: $NET [$PHY]" > /dev/kmsg
    disable_fw_log $PHY
    configure_ct $PHY
    set_ani $PHY 1
    set_rates $NET $DEVICE
  fi
fi
