#!/bin/sh /etc/rc.common

START=00
USE_PROCD=1
NAME=ServiceMonitor
PROG=/bin/$NAME
PIDFILE=/var/run/$NAME.pid

start_service() {
  procd_open_instance $NAME
  procd_set_param command $PROG
  procd_append_param command procd
  procd_append_param command $PIDFILE
  procd_append_param command 10m
  procd_append_param command 5m
  procd_set_param respawn
  procd_set_param stdout 0
  procd_set_param stderr 0
  procd_set_param pidfile $PIDFILE
  procd_close_instance
}
