#!/bin/sh /etc/rc.common

START=36
USE_PROCD=1
NAME=bootz
PROG=/bin/bootz

start_service() {
  procd_open_instance bootz
  procd_set_param command $PROG
  procd_append_param command boot
  procd_set_param stdout 0
  procd_set_param stderr 0
  procd_close_instance
}

reload_service() {
  echo "Explicitly restarting the '$NAME' service..."
  stop; start
}

stop_service() {
    $PROG fixup
}
